# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            diff_files=$(git diff HEAD~1 HEAD --name-only)
            echo "Files changed between HEAD and HEAD~1:"
            echo "$diff_files"
          else
            echo "No parent commit (HEAD~1) available."
          fi
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "$diff_files",
          echo test, and deploy your project.
